/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static java.awt.SystemColor.text;
import java.io.File;
import java.io.FileNotFoundException;
import java.time.Month;
import java.time.Year;
import java.util.Scanner;
import sun.security.provider.Sun;

/**
 *
 * @author Mike
 */
public class WeatherGUI extends javax.swing.JFrame {
    private Scanner inputFile;
    private String Year, Month, MaxT, MinT, AirF, Rain, Sun,  text;
    /**
     * Creates new form WeatherGUI
     */
    public WeatherGUI() {
        initComponents();
    }
    public void openFile() {
        try {
            inputFile = new Scanner(new File("src/Data/RingWayWeather.txt"));
        } // end try
        catch (FileNotFoundException fileNotFoundException) {
            System.err.println(fileNotFoundException);
            System.exit(1);
        } // end catch
    } // end method openFile
    public void printRecords() {
        text = "Year\tMonth\tMax Temp\tMin Temp\tAir Frost\tRainfall\tSunshine\n\n";

        try // read records from file using Scanner object
        {
            while (inputFile.hasNext()) {
                Year = inputFile.next();
                Month = inputFile.next();
                MaxT = inputFile.next();
                MinT = inputFile.next();
                AirF = inputFile.next();
                Rain = inputFile.next();
                Sun = inputFile.next();

                text += Year + "\t" + Month + "\t" + MaxT + "\t" + MinT + "\t" + AirF + "\t" + Rain + "\t" + Sun + "\n";
            } // end while
            txaReport.setText(text);
        } // end try
        catch (IllegalStateException stateException) {
            System.err.println(stateException);
            System.exit(1);
        } // end catch
    } // end method readRecords
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaReport = new javax.swing.JTextArea();
        OpenFile = new javax.swing.JButton();
        BtnTempMax = new javax.swing.JButton();
        BtnTempAvg = new javax.swing.JButton();
        BtnTempMin = new javax.swing.JButton();
        LblTemp = new javax.swing.JLabel();
        LblAirF = new javax.swing.JLabel();
        LblRain = new javax.swing.JLabel();
        LblSun = new javax.swing.JLabel();
        BtnAirFMax = new javax.swing.JButton();
        BtnAirFAvg = new javax.swing.JButton();
        BtnAirFMin = new javax.swing.JButton();
        BtnRainMax = new javax.swing.JButton();
        BtnRainMin = new javax.swing.JButton();
        BtnRainAvg = new javax.swing.JButton();
        BtnSunMax = new javax.swing.JButton();
        BtnSunMin = new javax.swing.JButton();
        BtnSunAvg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weather");
        setMinimumSize(new java.awt.Dimension(650, 200));
        setResizable(false);

        txaReport.setEditable(false);
        txaReport.setColumns(20);
        txaReport.setRows(5);
        jScrollPane1.setViewportView(txaReport);

        OpenFile.setText("Open File");
        OpenFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenFileMouseClicked(evt);
            }
        });

        BtnTempMax.setText("Max");

        BtnTempAvg.setText("Min");

        BtnTempMin.setText("Average");

        LblTemp.setText("Temp");

        LblAirF.setText("Air Frost");

        LblRain.setText("Rain Fall");

        LblSun.setText("Sunshine");

        BtnAirFMax.setText("Max");

        BtnAirFAvg.setText("Min");

        BtnAirFMin.setText("Average");

        BtnRainMax.setText("Max");

        BtnRainMin.setText("Min");

        BtnRainAvg.setText("Average");

        BtnSunMax.setText("Max");

        BtnSunMin.setText("Min");

        BtnSunAvg.setText("Average");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OpenFile)
                .addGap(285, 285, 285))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTemp)
                            .addComponent(BtnTempMax)
                            .addComponent(BtnTempAvg))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAirFMax)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblAirF)
                                        .addGap(279, 279, 279)
                                        .addComponent(LblSun))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnAirFAvg)
                                        .addGap(134, 134, 134)
                                        .addComponent(BtnRainMin)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnTempMin)
                        .addGap(88, 88, 88)
                        .addComponent(BtnAirFMin)
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnRainAvg)
                            .addComponent(BtnRainMax)
                            .addComponent(LblRain))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnSunMin)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(BtnSunAvg)
                                    .addGap(45, 45, 45))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BtnSunMax)
                                    .addContainerGap()))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OpenFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(LblTemp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnTempMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnTempMin)
                            .addComponent(BtnAirFMin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnTempAvg)
                            .addComponent(BtnAirFAvg)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LblSun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnSunMax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnSunAvg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnRainMin)
                                    .addComponent(BtnSunMin)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LblRain)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnRainMax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnRainAvg)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LblAirF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnAirFMax)
                                .addGap(58, 58, 58)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    
    private void OpenFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenFileMouseClicked
        openFile();
        printRecords();
        txaReport.setSelectionStart(0);
    }//GEN-LAST:event_OpenFileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeatherGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAirFAvg;
    private javax.swing.JButton BtnAirFMax;
    private javax.swing.JButton BtnAirFMin;
    private javax.swing.JButton BtnRainAvg;
    private javax.swing.JButton BtnRainMax;
    private javax.swing.JButton BtnRainMin;
    private javax.swing.JButton BtnSunAvg;
    private javax.swing.JButton BtnSunMax;
    private javax.swing.JButton BtnSunMin;
    private javax.swing.JButton BtnTempAvg;
    private javax.swing.JButton BtnTempMax;
    private javax.swing.JButton BtnTempMin;
    private javax.swing.JLabel LblAirF;
    private javax.swing.JLabel LblRain;
    private javax.swing.JLabel LblSun;
    private javax.swing.JLabel LblTemp;
    private javax.swing.JButton OpenFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaReport;
    // End of variables declaration//GEN-END:variables
}
